version: "3.8"
services:
  frontend:
    container_name: daimler-poc-web-stage
    image: daimler-poc/web-stage
    ports:
      - "7180:80"
    networks:
      front-tier-stage:
        ipv4_address: 172.16.239.10
  backend:
    container_name: daimler-poc-api-stage
    image: daimler-poc/api-stage
    ports:
      - "7181:8081"
    networks:
      front-tier-stage:
        ipv4_address: 172.16.239.11
networks:
  front-tier-stage:
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"
