version: "3.8"
services:
  frontend:
    container_name: daimler-poc-web-prod
    image: daimler-poc/web-prod
    ports:
      - "7280:80"
    networks:
      front-tier-prod:
        ipv4_address: 172.16.240.10
  backend:
    container_name: daimler-poc-api-prod
    image: daimler-poc/api-prod
    ports:
      - "7281:8081"
    networks:
      front-tier-prod:
        ipv4_address: 172.16.240.11
networks:
  front-tier-prod:
    ipam:
      driver: default
      config:
        - subnet: "172.16.240.0/24"
